---

- name: Add Users
  hosts: all
  become: true
  pre_tasks:

    - name: update repo
      apt:
        upgrade: dist
        update_cache: yes
  
- hosts: all
  become: true
  tasks:

    - name: Create Group
      group:
        name: developers
        state: present

    - name: Create users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        create_home: true
        shell: /bin/bash
      with_items:
         - name: "Viraj"
           groups: sudo,developers
         - name: "Saman"
           groups: sudo,developers

    - name: Add ssh key for ansible_user
      authorized_key:
        user: ansible_user
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/{{ item.name}}.pub') }}"
      with_items:
        - name: "Viraj"
          groups: sudo,developers
        - name: "Saman"
          groups: sudo,developers
